baseurl = "https://example.com/"
languageCode = "zh-cn"
theme = "terminal"
paginate = 5
defaultContentLanguage = "zh-cn"
title = "/var/log/waka-kanou"

[languages]
  [languages.zh-cn]
    title = "/var/log/waka-kanou"
    subtitle = "「若叶の日志」"
    keywords = ""
    copyright = ""
    menuMore = "查看更多"
    readMore = "阅读此文"
    readOtherPosts = "查看其他文章"

    [languages.zh-cn.params]
      contentTypeName = "posts"
      themeColor = "blue"
      showMenuItems = 2
      fullWidthTheme = false
      centerTheme = true

    [languages.zh-cn.params.logo]
      logoText = "# ls /var/log/waka-kanou"
      logoHomeLink = "/"

    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        identifier = "about"
        name = "「关于」"
        url = "/about"
  [languages.en]
    title = "/var/log/waka-kanou"
    subtitle = "Blog of Waka Kanou"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params]
      contentTypeName = "posts"
      themeColor = "blue"
      showMenuItems = 2
      fullWidthTheme = false
      centerTheme = true


    [languages.en.params.logo]
      logoText = "# ls /var/log/waka-kanou"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
