baseurl = "https://owow.cc/"
languageCode = "zh-cn"
theme = "terminal"
paginate = 5
defaultContentLanguage = "zh-cn"
title = "/var/log/waka-kanou"
staticDir = ["static"]

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  fullWidthTheme = false
  centerTheme = true
  [params.logo]
    logoText = "/var/log/waka-kanou"

[languages]
  [languages.zh-cn]
    [languages.zh-cn.params]
      subtitle = "「若叶の日志」"
      keywords = "TurboHsu, Blog, IT, Web, Programming, Golang, Linux"
      menuMore = "查看更多"
      readMore = "阅读此文"
      readOtherPosts = "查看其他文章"

  [languages.en]
    [languages.en.params]
      subtitle = "Blog of Waka Kanou"
      keywords = "TurboHsu, Blog, IT, Web, Programming, Golang, Linux"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Tags"
  weight = 1000
  identifier = "tags"
  url = "/tags/"