baseurl = "https://owow.cc/"
languageCode = "zh-cn"
theme = "terminal"
paginate = 5
defaultContentLanguage = "zh-cn"
title = "/var/log/waka-kanou"

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  fullWidthTheme = false
  centerTheme = true
  [params.logo]
    logoText = "/var/log/waka-kanou"

[languages]
  [languages.zh-cn]
    [languages.zh-cn.params]
      subtitle = "「若叶の日志」"
      keywords = ""
      menuMore = "查看更多"
      readMore = "阅读此文"
      readOtherPosts = "查看其他文章"

  [languages.en]
    [languages.en.params]
      subtitle = "Blog of Waka Kanou"
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"